/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import static biblioteca.Biblioteca.con;
import biblioteca.Livro;
import conexaomysql.ConexaoMySql;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernanda
 */
public class NovoLivro extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovoLivro
     * 
     */
    
    public Livro livro;
    
    public NovoLivro() {
        initComponents();
        livro = new Livro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoAddLivro = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lbAutor = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        lbEditora = new javax.swing.JLabel();
        txtEditora = new javax.swing.JTextField();
        lbLancamento = new javax.swing.JLabel();
        lbEdicao = new javax.swing.JLabel();
        txtEdicao = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        lbFigura = new javax.swing.JLabel();
        txtLancamento = new javax.swing.JTextField();

        setClosable(true);

        fundoAddLivro.setBorder(javax.swing.BorderFactory.createTitledBorder("Adcionar livro"));

        lbTitulo.setText("TITULO:");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        lbAutor.setText("AUTOR:");

        lbEditora.setText("EDITORA:");

        lbLancamento.setText("LANÇAMENTO:");

        lbEdicao.setText("EDIÇÃO:");

        txtEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdicaoActionPerformed(evt);
            }
        });

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lbFigura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/Icones/neeeew.png"))); // NOI18N

        txtLancamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLancamentoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout fundoAddLivroLayout = new javax.swing.GroupLayout(fundoAddLivro);
        fundoAddLivro.setLayout(fundoAddLivroLayout);
        fundoAddLivroLayout.setHorizontalGroup(
            fundoAddLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoAddLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundoAddLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fundoAddLivroLayout.createSequentialGroup()
                        .addGroup(fundoAddLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitulo)
                            .addComponent(lbAutor)
                            .addComponent(lbEditora)
                            .addComponent(lbLancamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fundoAddLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoAddLivroLayout.createSequentialGroup()
                                .addComponent(txtLancamento, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbEdicao)
                                .addGap(18, 18, 18)
                                .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEditora)
                            .addComponent(txtTitulo)
                            .addComponent(txtAutor))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(lbFigura)
                .addContainerGap())
        );
        fundoAddLivroLayout.setVerticalGroup(
            fundoAddLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoAddLivroLayout.createSequentialGroup()
                .addGroup(fundoAddLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoAddLivroLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(fundoAddLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTitulo)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(fundoAddLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAutor)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoAddLivroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbFigura)
                        .addGap(12, 12, 12)))
                .addGroup(fundoAddLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEditora)
                    .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fundoAddLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLancamento)
                    .addComponent(lbEdicao)
                    .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoAddLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fundoAddLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdicaoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        livro.setTitulo(txtTitulo.getText());
        livro.setAutor(txtAutor.getText());
        livro.setEditora(txtEditora.getText());        
        livro.setEdicao(Integer.parseInt(txtEdicao.getText()));
        livro.setDataLancamento(Integer.parseInt(txtLancamento.getText()));
        
        if (!livro.getTitulo().equals("") && !livro.getAutor().equals("") && !livro.getEditora().equals("")) {
            /*Statement stm =ConexaoMySql.con.createStatement();
            stm.executeUpdate(sqlInsert);*/
            
            livro.inserir();
            JOptionPane.showMessageDialog(null,null,
                    "Livro Cadastrado com Sucesso!",
                    JOptionPane.INFORMATION_MESSAGE);
            txtTitulo.setText("");
            txtAutor.setText("");
            txtEditora.setText("");
            txtLancamento.setText("");
            txtEdicao.setText("");
            }
            else {
                JOptionPane.showMessageDialog(null,
                            "Preencha todos os campos!",
                            "Erro!",
                            JOptionPane.ERROR_MESSAGE);                
            

    }        

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtLancamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLancamentoKeyTyped
        int numero=4;
        if(txtLancamento.getText().length()>=numero){
            evt.consume();
        }
    }//GEN-LAST:event_txtLancamentoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JPanel fundoAddLivro;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbEdicao;
    private javax.swing.JLabel lbEditora;
    private javax.swing.JLabel lbFigura;
    private javax.swing.JLabel lbLancamento;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEdicao;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtLancamento;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
